#define GIMBAL_1_HI_LIMIT 22
#define GIMBAL_1_LOW_LIMIT 23
#define GIMBAL_1_LVDT 10
#define GIMBAL_1_STEP 1
#define GIMBAL_1_DIR 0

#define GIMBAL_2_HI_LIMIT 20
#define GIMBAL_2_LOW_LIMIT 21
#define GIMBAL_2_LVDT 11
#define GIMBAL_2_STEP 5
#define GIMBAL_2_DIR 2

#define GIMBAL_3_HI_LIMIT 16
#define GIMBAL_3_LOW_LIMIT 17
#define GIMBAL_3_LVDT 12
#define GIMBAL_3_STEP 7
#define GIMBAL_3_DIR 6

#define GIMBAL_4_HI_LIMIT 14
#define GIMBAL_4_LOW_LIMIT 15
#define GIMBAL_4_LVDT 13
#define GIMBAL_4_STEP 9
#define GIMBAL_4_DIR 8

#define LBRAKE_HI_LIMIT 32
#define LBRAKE_LOW_LIMIT 33
#define LBRAKE_LVDT 14
#define LBRAKE_STEP 24
#define LBRAKE_DIR 12

#define RBRAKE_HI_LIMIT 30
#define RBRAKE_LOW_LIMIT 31
#define RBRAKE_LVDT 16
#define RBRAKE_STEP 26
#define RBRAKE_DIR 25
